#!groovy

pipeline {
  agent any

  stages {
    stage('FetchCode'){
      steps {
        git url: "https://github.com/frickjack/misc-stuff.git"
      }
    }
    stage('Prep') {
      steps {
        dir('Terraform/JenkinsTest') {
          sh 'terraform init -backend-config /mnt/secrets/terraform/JenkinsTest.backend.tfvars'
        }
      }
    }
    stage('Plan') {
      steps {
        dir('Terraform/JenkinsTest') {
          echo 'Planning ...'
          sh 'terraform plan --var-file /mnt/secrets/terraform/aws.tfvars'
        }
      }
    }
    stage('TearDown') {
      steps {
        echo 'TearDown....'
      }
    }
  }
}
